### ISSUE TITLE
Unstash pipeline step hangs frequently

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-artifact-manager-plugin#11]
<p>Jenkins: 2.190.1</p>

<p>Azure Artifact Manager plugin: 2.121.3</p>

<p>Running a build with several parallel steps the unstash step for an Azure-stored artifact hangs indefinitely. This blocks the usage of this plugin, at least in out case.</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Stack traces after aborting one of the jobs:

16:56:32  java.lang.InterruptedException
16:56:32  java.lang.InterruptedException
16:56:32   at java.lang.<span class="code-object">Object</span>.wait(Native Method)
16:56:32   at hudson.remoting.Request.call(Request.java:177)
16:56:32   at hudson.remoting.Channel.call(Channel.java:956)
16:56:32   at hudson.FilePath.act(FilePath.java:1072)
16:56:32   at hudson.FilePath.act(FilePath.java:1061)
16:56:32   at hudson.FilePath.untarFrom(FilePath.java:800)
16:56:32   at com.microsoft.jenkins.artifactmanager.AzureArtifactManager.unstash(AzureArtifactManager.java:281)
16:56:32   at org.jenkinsci.plugins.workflow.flow.StashManager.unstash(StashManager.java:158)
16:56:32   at org.jenkinsci.plugins.workflow.support.steps.stash.UnstashStep$Execution.run(UnstashStep.java:76)
16:56:32   at org.jenkinsci.plugins.workflow.support.steps.stash.UnstashStep$Execution.run(UnstashStep.java:63)
16:56:32   at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
16:56:32   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
16:56:32   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16:56:32   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:56:32   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:56:32   at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748)
16:56:32  java.lang.InterruptedException
16:56:32   at java.lang.<span class="code-object">Object</span>.wait(Native Method)
16:56:32   at hudson.remoting.Request.call(Request.java:177)
16:56:32   at hudson.remoting.Channel.call(Channel.java:956)
16:56:32   at hudson.FilePath.act(FilePath.java:1072)
16:56:32   at hudson.FilePath.act(FilePath.java:1061)
16:56:32   at hudson.FilePath.untarFrom(FilePath.java:800)
16:56:32   at com.microsoft.jenkins.artifactmanager.AzureArtifactManager.unstash(AzureArtifactManager.java:281)
16:56:32   at org.jenkinsci.plugins.workflow.flow.StashManager.unstash(StashManager.java:158)
16:56:32   at org.jenkinsci.plugins.workflow.support.steps.stash.UnstashStep$Execution.run(UnstashStep.java:76)
16:56:32   at org.jenkinsci.plugins.workflow.support.steps.stash.UnstashStep$Execution.run(UnstashStep.java:63)
16:56:32   at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
16:56:32   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
16:56:32   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16:56:32   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:56:32   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:56:32   at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748)
16:56:32  java.lang.InterruptedException
16:56:32   at java.lang.<span class="code-object">Object</span>.wait(Native Method)
16:56:32   at hudson.remoting.Request.call(Request.java:177)
16:56:32   at hudson.remoting.Channel.call(Channel.java:956)
16:56:32   at hudson.FilePath.act(FilePath.java:1072)
16:56:32   at hudson.FilePath.act(FilePath.java:1061)
16:56:32   at hudson.FilePath.untarFrom(FilePath.java:800)
16:56:32   at com.microsoft.jenkins.artifactmanager.AzureArtifactManager.unstash(AzureArtifactManager.java:281)
16:56:32   at org.jenkinsci.plugins.workflow.flow.StashManager.unstash(StashManager.java:158)
16:56:32   at org.jenkinsci.plugins.workflow.support.steps.stash.UnstashStep$Execution.run(UnstashStep.java:76)
16:56:32   at org.jenkinsci.plugins.workflow.support.steps.stash.UnstashStep$Execution.run(UnstashStep.java:63)
16:56:32   at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
16:56:32   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
16:56:32   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16:56:32   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:56:32   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:56:32   at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748)
16:56:32  java.lang.InterruptedException
16:56:32   at java.lang.<span class="code-object">Object</span>.wait(Native Method)
16:56:32   at hudson.remoting.Request.call(Request.java:177)
16:56:32   at hudson.remoting.Channel.call(Channel.java:956)
16:56:32   at hudson.FilePath.act(FilePath.java:1072)
16:56:32   at hudson.FilePath.act(FilePath.java:1061)
16:56:32   at hudson.FilePath.untarFrom(FilePath.java:800)
16:56:32   at com.microsoft.jenkins.artifactmanager.AzureArtifactManager.unstash(AzureArtifactManager.java:281)
16:56:32   at org.jenkinsci.plugins.workflow.flow.StashManager.unstash(StashManager.java:158)
16:56:32   at org.jenkinsci.plugins.workflow.support.steps.stash.UnstashStep$Execution.run(UnstashStep.java:76)
16:56:32   at org.jenkinsci.plugins.workflow.support.steps.stash.UnstashStep$Execution.run(UnstashStep.java:63)
16:56:32   at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
16:56:32   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
16:56:32   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16:56:32   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:56:32   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:56:32   at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748)</pre>
</div></div>
<i>[JENKINS-60212] created by megaloni</i>

**Comment by timja** [comment]
Likely fixed in https://github.com/jenkinsci/azure-artifact-manager-plugin/pull/15
